apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${project.artifactId}
spec:
  template:
    spec:
      containers:
        - imagePullPolicy: Always
          resources:
            limits:
              cpu: 1000m
              memory: 768Mi
            requests:
              cpu: 100m
              memory: 256Mi
