apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: ${project.artifactId}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: ${project.artifactId}
  minReplicas: 2
  maxReplicas: 4
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 60 # Delay downscaling by 1 min
    scaleUp:
      stabilizationWindowSeconds: 60 # Delay upscaling by 1 min
