name: Opentofu and Quarkus Full Deployment
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  opentofu:
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      TF_VAR_aws_state_bucket: ${{ secrets.TF_VAR_AWS_STATE_BUCKET }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up OpenTofu
        uses: opentofu/setup-opentofu@v1
        with:
          tofu_version: latest
          tofu_wrapper: false
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Run Trivy security scan (IaC)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "config"
          scan-ref: aws-infra
          format: "table"
          exit-code: "0"
          severity: 'CRITICAL,HIGH'
      - name: Tofu Init
        run: tofu init
        working-directory: aws-infra
      - name: Tofu Validate
        run: tofu validate
        working-directory: aws-infra
      - name: Tofu Plan
        run: tofu plan -out=aws.tfplan
        working-directory: aws-infra
      - name: Tofu Apply
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: tofu apply -auto-approve aws.tfplan
        working-directory: aws-infra
  quarkus:
    needs: opentofu
    runs-on: ubuntu-latest
    env:
      AWS_REGION: us-east-1
      DOCKER_REGISTRY: ${{ vars.DOCKER_REGISTRY }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'maven'
      - name: Run Maven tests
        run: ./mvnw verify
        working-directory: quarkus-cloud-native-workload
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      - name: Docker build
        run: ./mvnw k8s:build
        working-directory: quarkus-cloud-native-workload
      - name: Run Trivy security scan (Docker)
        uses: aquasecurity/trivy-action@0.28.0
        with:
          scan-type: "image"
          image-ref: quarkus-cloud-native-workload:latest
          format: "table"
          exit-code: "0"
          severity: 'CRITICAL,HIGH'
      - name: Docker push
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: ./mvnw k8s:push
        working-directory: quarkus-cloud-native-workload